# Secret for MongoDB credentials
# b64enc = base64 encode the value from values.yaml automatically
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels: {{- include "ms.labels" . | nindent 4 }}
type: Opaque
data:
  # .Values.secrets.mongo.username = "admin" → b64enc → "YWRtaW4="
  mongo-root-username: {{ .Values.secrets.mongo.username | b64enc }}
  mongo-root-password: {{ .Values.secrets.mongo.password | b64enc }}
---
# Secret for SQL Server SA password
apiVersion: v1
kind: Secret
metadata:
  name: sqldata-secret
  labels: {{- include "ms.labels" . | nindent 4 }}
type: Opaque
data:
  sa-password: {{ .Values.secrets.sql.saPassword | b64enc }}
