apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/mina-john-emil/.NET-Microservices-Sample-mina.git
    targetRevision: main
    path: helm/microservices
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.imageTag
          value: "latest"
        - name: global.vmIP
          value: "192.168.150.135"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true        # delete resources removed from git
      selfHeal: true     # auto-fix drift
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
